version: "3"

services:

  server:
    restart : always
    container_name: "server-pd"
    ports:
      - "8080:8080"
    build:
      context: "BackEnd"
    networks:
      - red-disign-patterns

  mariadb:
    restart : always
    container_name: "mariadb-pd"
    ports:
      - "3320:3306"
    volumes:
      - "./mariadb/data:/var/lib/mysql"
      - "./mariadb/database.sql:/docker-entrypoint-initdb.d/database.sql"
    environment:
      - MARIADB_ROOT_PASSWORD=secret_root_?2172
      - MARIADB_USER=Administrador
      - MARIADB_PASSWORD=secret_administrador_?2172
    image: 'mariadb:latest'
    networks:
      - red-disign-patterns

networks:
  red-disign-patterns:
    name: servidor-nginx_red-disign-patterns
    external: true